apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver-lb
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: ${K8S_API_LB_POOL_START}
  ports:
  - name: https
    port: 6443
    targetPort: 6443
  selector:
    component: kube-apiserver
